###### OpenAI API Configuration ######
# To get your API key, sign up at https://platform.openai.com/signup or log in at https://platform.openai.com/login
gpt_api_key: "gpt_api_key"
api_endpoint: "https://api.openai.com/v1/chat/completions"
model: "gpt-4o-mini"
max_tokens: 3000
temperature: 1

###### Discourse Configuration ######
# To get your API key, go to https://discourse.example.com/admin/api/keys
# replace "discourse.example.com" with your Discourse URL
discourse_api_key: "discourse_api_key"
discourse_api_username: "discourse_api_username"
discourse_base_url: "https://discourse.example.com"
# To get your category ID, go to https://discourse.example.com/c/your-category-name.json
unsorted_category_id: 9 # The category ID for the unsorted category
